/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as GraciasOrderNumberRouteImport } from './routes/gracias.$orderNumber'
import { Route as ApiGenerateProductImageRouteImport } from './routes/api/generate-product-image'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasOrderNumberRoute = GraciasOrderNumberRouteImport.update({
  id: '/gracias/$orderNumber',
  path: '/gracias/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateProductImageRoute = ApiGenerateProductImageRouteImport.update({
  id: '/api/generate-product-image',
  path: '/api/generate-product-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/api/generate-product-image': typeof ApiGenerateProductImageRoute
  '/gracias/$orderNumber': typeof GraciasOrderNumberRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/api/generate-product-image': typeof ApiGenerateProductImageRoute
  '/gracias/$orderNumber': typeof GraciasOrderNumberRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/api/generate-product-image': typeof ApiGenerateProductImageRoute
  '/gracias/$orderNumber': typeof GraciasOrderNumberRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/api/generate-product-image'
    | '/gracias/$orderNumber'
    | '/producto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/api/generate-product-image'
    | '/gracias/$orderNumber'
    | '/producto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/api/generate-product-image'
    | '/gracias/$orderNumber'
    | '/producto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiGenerateProductImageRoute: typeof ApiGenerateProductImageRoute
  GraciasOrderNumberRoute: typeof GraciasOrderNumberRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias/$orderNumber': {
      id: '/gracias/$orderNumber'
      path: '/gracias/$orderNumber'
      fullPath: '/gracias/$orderNumber'
      preLoaderRoute: typeof GraciasOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-product-image': {
      id: '/api/generate-product-image'
      path: '/api/generate-product-image'
      fullPath: '/api/generate-product-image'
      preLoaderRoute: typeof ApiGenerateProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ApiGenerateProductImageRoute: ApiGenerateProductImageRoute,
  GraciasOrderNumberRoute: GraciasOrderNumberRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
